/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Mon Dec 11 00:21:17 2017. */

#include "elegoo.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Command_fields[6] = {
    PB_FIELD(  1, SINT32  , SINGULAR, STATIC  , FIRST, Command, SpeedR, SpeedR, 0),
    PB_FIELD(  2, SINT32  , SINGULAR, STATIC  , OTHER, Command, SpeedL, SpeedR, 0),
    PB_FIELD(  3, BOOL    , SINGULAR, STATIC  , OTHER, Command, Stop, SpeedL, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, Command, Direction, Stop, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, Command, StopAfter, Direction, 0),
    PB_LAST_FIELD
};

const pb_field_t Events_fields[8] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, Events, Distance, Distance, 0),
    PB_FIELD(  2, SINT32  , SINGULAR, STATIC  , OTHER, Events, Direction, Distance, 0),
    PB_FIELD(  3, BOOL    , SINGULAR, STATIC  , OTHER, Events, SensorR, Direction, 0),
    PB_FIELD(  4, BOOL    , SINGULAR, STATIC  , OTHER, Events, SensorC, SensorR, 0),
    PB_FIELD(  5, BOOL    , SINGULAR, STATIC  , OTHER, Events, SensorL, SensorC, 0),
    PB_FIELD(  6, UINT32  , SINGULAR, STATIC  , OTHER, Events, KeyPress, SensorL, 0),
    PB_FIELD(  7, UINT32  , SINGULAR, STATIC  , OTHER, Events, Time, KeyPress, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
