/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Tue Dec 26 00:06:46 2017. */

#ifndef PB_ELEGOO_ELEGOO_PB_H_INCLUDED
#define PB_ELEGOO_ELEGOO_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _elegoo_Remote {
    uint32_t Key;
/* @@protoc_insertion_point(struct:elegoo_Remote) */
} elegoo_Remote;

typedef struct _elegoo_Sensor {
    bool R;
    bool C;
    bool L;
/* @@protoc_insertion_point(struct:elegoo_Sensor) */
} elegoo_Sensor;

typedef struct _elegoo_Sonar {
    uint32_t Distance;
    int32_t Direction;
/* @@protoc_insertion_point(struct:elegoo_Sonar) */
} elegoo_Sonar;

typedef struct _elegoo_Speed {
    int32_t L;
    int32_t R;
    uint32_t StopAfter;
/* @@protoc_insertion_point(struct:elegoo_Speed) */
} elegoo_Speed;

typedef struct _elegoo_Command {
    elegoo_Speed Speed;
    int32_t Look;
/* @@protoc_insertion_point(struct:elegoo_Command) */
} elegoo_Command;

typedef struct _elegoo_Event {
    uint32_t TimeStamp;
    elegoo_Sonar Head;
    elegoo_Sensor Sensor;
    elegoo_Remote Remote;
/* @@protoc_insertion_point(struct:elegoo_Event) */
} elegoo_Event;

/* Default values for struct fields */

/* Initializer values for message structs */
#define elegoo_Speed_init_default                {0, 0, 0}
#define elegoo_Command_init_default              {elegoo_Speed_init_default, 0}
#define elegoo_Sonar_init_default                {0, 0}
#define elegoo_Sensor_init_default               {0, 0, 0}
#define elegoo_Remote_init_default               {0}
#define elegoo_Event_init_default                {0, elegoo_Sonar_init_default, elegoo_Sensor_init_default, elegoo_Remote_init_default}
#define elegoo_Speed_init_zero                   {0, 0, 0}
#define elegoo_Command_init_zero                 {elegoo_Speed_init_zero, 0}
#define elegoo_Sonar_init_zero                   {0, 0}
#define elegoo_Sensor_init_zero                  {0, 0, 0}
#define elegoo_Remote_init_zero                  {0}
#define elegoo_Event_init_zero                   {0, elegoo_Sonar_init_zero, elegoo_Sensor_init_zero, elegoo_Remote_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define elegoo_Remote_Key_tag                    1
#define elegoo_Sensor_R_tag                      1
#define elegoo_Sensor_C_tag                      2
#define elegoo_Sensor_L_tag                      3
#define elegoo_Sonar_Distance_tag                1
#define elegoo_Sonar_Direction_tag               2
#define elegoo_Speed_L_tag                       1
#define elegoo_Speed_R_tag                       2
#define elegoo_Speed_StopAfter_tag               3
#define elegoo_Command_Speed_tag                 1
#define elegoo_Command_Look_tag                  2
#define elegoo_Event_TimeStamp_tag               1
#define elegoo_Event_Head_tag                    2
#define elegoo_Event_Sensor_tag                  3
#define elegoo_Event_Remote_tag                  4

/* Struct field encoding specification for nanopb */
extern const pb_field_t elegoo_Speed_fields[4];
extern const pb_field_t elegoo_Command_fields[3];
extern const pb_field_t elegoo_Sonar_fields[3];
extern const pb_field_t elegoo_Sensor_fields[4];
extern const pb_field_t elegoo_Remote_fields[2];
extern const pb_field_t elegoo_Event_fields[5];

/* Maximum encoded size of messages (where known) */
#define elegoo_Speed_size                        18
#define elegoo_Command_size                      26
#define elegoo_Sonar_size                        12
#define elegoo_Sensor_size                       6
#define elegoo_Remote_size                       6
#define elegoo_Event_size                        36

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define ELEGOO_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
