// Code generated by protoc-gen-go. DO NOT EDIT.
// source: elegoo.proto

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	elegoo.proto

It has these top-level messages:
	Speed
	Command
	Sensor
	Events
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Speed struct {
	L int32 `protobuf:"zigzag32,1,opt,name=L" json:"L,omitempty"`
	R int32 `protobuf:"zigzag32,2,opt,name=R" json:"R,omitempty"`
}

func (m *Speed) Reset()                    { *m = Speed{} }
func (m *Speed) String() string            { return proto.CompactTextString(m) }
func (*Speed) ProtoMessage()               {}
func (*Speed) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Speed) GetL() int32 {
	if m != nil {
		return m.L
	}
	return 0
}

func (m *Speed) GetR() int32 {
	if m != nil {
		return m.R
	}
	return 0
}

type Command struct {
	Speed     *Speed `protobuf:"bytes,1,opt,name=Speed" json:"Speed,omitempty"`
	Stop      bool   `protobuf:"varint,3,opt,name=Stop" json:"Stop,omitempty"`
	Direction uint32 `protobuf:"varint,4,opt,name=Direction" json:"Direction,omitempty"`
	StopAfter uint32 `protobuf:"varint,5,opt,name=StopAfter" json:"StopAfter,omitempty"`
}

func (m *Command) Reset()                    { *m = Command{} }
func (m *Command) String() string            { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()               {}
func (*Command) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Command) GetSpeed() *Speed {
	if m != nil {
		return m.Speed
	}
	return nil
}

func (m *Command) GetStop() bool {
	if m != nil {
		return m.Stop
	}
	return false
}

func (m *Command) GetDirection() uint32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

func (m *Command) GetStopAfter() uint32 {
	if m != nil {
		return m.StopAfter
	}
	return 0
}

type Sensor struct {
	R bool `protobuf:"varint,1,opt,name=R" json:"R,omitempty"`
	C bool `protobuf:"varint,2,opt,name=C" json:"C,omitempty"`
	L bool `protobuf:"varint,3,opt,name=L" json:"L,omitempty"`
}

func (m *Sensor) Reset()                    { *m = Sensor{} }
func (m *Sensor) String() string            { return proto.CompactTextString(m) }
func (*Sensor) ProtoMessage()               {}
func (*Sensor) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Sensor) GetR() bool {
	if m != nil {
		return m.R
	}
	return false
}

func (m *Sensor) GetC() bool {
	if m != nil {
		return m.C
	}
	return false
}

func (m *Sensor) GetL() bool {
	if m != nil {
		return m.L
	}
	return false
}

type Events struct {
	Distance  uint32  `protobuf:"varint,1,opt,name=Distance" json:"Distance,omitempty"`
	Direction int32   `protobuf:"zigzag32,2,opt,name=Direction" json:"Direction,omitempty"`
	Sensor    *Sensor `protobuf:"bytes,3,opt,name=Sensor" json:"Sensor,omitempty"`
	KeyPress  uint32  `protobuf:"varint,6,opt,name=KeyPress" json:"KeyPress,omitempty"`
	Time      uint32  `protobuf:"varint,7,opt,name=Time" json:"Time,omitempty"`
}

func (m *Events) Reset()                    { *m = Events{} }
func (m *Events) String() string            { return proto.CompactTextString(m) }
func (*Events) ProtoMessage()               {}
func (*Events) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Events) GetDistance() uint32 {
	if m != nil {
		return m.Distance
	}
	return 0
}

func (m *Events) GetDirection() int32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

func (m *Events) GetSensor() *Sensor {
	if m != nil {
		return m.Sensor
	}
	return nil
}

func (m *Events) GetKeyPress() uint32 {
	if m != nil {
		return m.KeyPress
	}
	return 0
}

func (m *Events) GetTime() uint32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func init() {
	proto.RegisterType((*Speed)(nil), "elegoo.Speed")
	proto.RegisterType((*Command)(nil), "elegoo.Command")
	proto.RegisterType((*Sensor)(nil), "elegoo.Sensor")
	proto.RegisterType((*Events)(nil), "elegoo.Events")
}

func init() { proto.RegisterFile("elegoo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xb1, 0x4e, 0x84, 0x40,
	0x10, 0x86, 0x33, 0xca, 0xed, 0xe1, 0xde, 0x61, 0xe2, 0x56, 0x9b, 0x8b, 0x05, 0xc1, 0xc4, 0x50,
	0x5d, 0x81, 0x4f, 0xa0, 0x9c, 0x95, 0x14, 0x66, 0xb0, 0xb2, 0xc3, 0xbb, 0xd1, 0x90, 0xc8, 0x2e,
	0x81, 0x8d, 0x89, 0x8d, 0x0f, 0xe2, 0xd3, 0x9a, 0x9d, 0x3d, 0x50, 0xbb, 0xf9, 0xfe, 0x19, 0xfe,
	0xf9, 0x87, 0x95, 0x6b, 0x7a, 0xa7, 0x37, 0x6b, 0xb7, 0xfd, 0x60, 0x9d, 0x55, 0x22, 0x50, 0x76,
	0x25, 0x17, 0x75, 0x4f, 0x74, 0x50, 0x6b, 0x09, 0x95, 0x86, 0x14, 0xf2, 0x0b, 0x84, 0xca, 0x13,
	0xea, 0x93, 0x40, 0x98, 0x7d, 0xc9, 0x65, 0x69, 0xbb, 0xae, 0x31, 0x07, 0x35, 0xcd, 0xf3, 0xe8,
	0xaa, 0x48, 0xb6, 0x47, 0x57, 0x16, 0xf1, 0xe8, 0xa5, 0x64, 0x54, 0x3b, 0xdb, 0xeb, 0xd3, 0x14,
	0xf2, 0x18, 0xb9, 0x56, 0x97, 0xf2, 0x6c, 0xd7, 0x0e, 0xb4, 0x77, 0xad, 0x35, 0x3a, 0x4a, 0x21,
	0x4f, 0xf0, 0x57, 0xf0, 0x5d, 0x3f, 0x75, 0xfb, 0xea, 0x68, 0xd0, 0x8b, 0xd0, 0x9d, 0x85, 0xac,
	0x90, 0xa2, 0x26, 0x33, 0xda, 0x21, 0xe4, 0x02, 0xb6, 0x05, 0xf4, 0x54, 0x72, 0xca, 0x18, 0xa1,
	0x0c, 0x17, 0x84, 0x95, 0x50, 0x65, 0xdf, 0x20, 0xc5, 0xfd, 0x07, 0x19, 0x37, 0xaa, 0x8d, 0x8c,
	0x77, 0xed, 0xe8, 0x1a, 0xb3, 0x27, 0xfe, 0x36, 0xc1, 0x99, 0xff, 0xc7, 0x0a, 0x07, 0xff, 0x89,
	0x75, 0x3d, 0x2d, 0x66, 0xdf, 0x55, 0x71, 0x3e, 0x9f, 0xcb, 0x2a, 0x4e, 0xb1, 0x36, 0x32, 0x7e,
	0xa0, 0xcf, 0xc7, 0x81, 0xc6, 0x51, 0x8b, 0xb0, 0x61, 0x62, 0xff, 0x33, 0x9e, 0xda, 0x8e, 0xf4,
	0x92, 0x75, 0xae, 0xef, 0xc4, 0x73, 0xd4, 0x35, 0xad, 0x79, 0x11, 0xfc, 0x18, 0x37, 0x3f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x90, 0x19, 0xf0, 0xc2, 0x9c, 0x01, 0x00, 0x00,
}
