// Code generated by protoc-gen-go. DO NOT EDIT.
// source: elegoo.proto

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	elegoo.proto

It has these top-level messages:
	Speed
	Command
	UltraSonic
	InfraRed
	RemoteControl
	Event
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Speed struct {
	L int32 `protobuf:"zigzag32,1,opt,name=L" json:"L,omitempty"`
	R int32 `protobuf:"zigzag32,2,opt,name=R" json:"R,omitempty"`
}

func (m *Speed) Reset()                    { *m = Speed{} }
func (m *Speed) String() string            { return proto.CompactTextString(m) }
func (*Speed) ProtoMessage()               {}
func (*Speed) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Speed) GetL() int32 {
	if m != nil {
		return m.L
	}
	return 0
}

func (m *Speed) GetR() int32 {
	if m != nil {
		return m.R
	}
	return 0
}

type Command struct {
	Speed     *Speed `protobuf:"bytes,1,opt,name=Speed" json:"Speed,omitempty"`
	Stop      bool   `protobuf:"varint,3,opt,name=Stop" json:"Stop,omitempty"`
	Look      uint32 `protobuf:"varint,4,opt,name=Look" json:"Look,omitempty"`
	StopAfter uint32 `protobuf:"varint,5,opt,name=StopAfter" json:"StopAfter,omitempty"`
}

func (m *Command) Reset()                    { *m = Command{} }
func (m *Command) String() string            { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()               {}
func (*Command) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Command) GetSpeed() *Speed {
	if m != nil {
		return m.Speed
	}
	return nil
}

func (m *Command) GetStop() bool {
	if m != nil {
		return m.Stop
	}
	return false
}

func (m *Command) GetLook() uint32 {
	if m != nil {
		return m.Look
	}
	return 0
}

func (m *Command) GetStopAfter() uint32 {
	if m != nil {
		return m.StopAfter
	}
	return 0
}

type UltraSonic struct {
	Distance  uint32 `protobuf:"varint,1,opt,name=Distance" json:"Distance,omitempty"`
	Direction int32  `protobuf:"zigzag32,2,opt,name=Direction" json:"Direction,omitempty"`
}

func (m *UltraSonic) Reset()                    { *m = UltraSonic{} }
func (m *UltraSonic) String() string            { return proto.CompactTextString(m) }
func (*UltraSonic) ProtoMessage()               {}
func (*UltraSonic) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UltraSonic) GetDistance() uint32 {
	if m != nil {
		return m.Distance
	}
	return 0
}

func (m *UltraSonic) GetDirection() int32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

type InfraRed struct {
	R bool `protobuf:"varint,1,opt,name=R" json:"R,omitempty"`
	C bool `protobuf:"varint,2,opt,name=C" json:"C,omitempty"`
	L bool `protobuf:"varint,3,opt,name=L" json:"L,omitempty"`
}

func (m *InfraRed) Reset()                    { *m = InfraRed{} }
func (m *InfraRed) String() string            { return proto.CompactTextString(m) }
func (*InfraRed) ProtoMessage()               {}
func (*InfraRed) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *InfraRed) GetR() bool {
	if m != nil {
		return m.R
	}
	return false
}

func (m *InfraRed) GetC() bool {
	if m != nil {
		return m.C
	}
	return false
}

func (m *InfraRed) GetL() bool {
	if m != nil {
		return m.L
	}
	return false
}

type RemoteControl struct {
	Key uint32 `protobuf:"varint,1,opt,name=Key" json:"Key,omitempty"`
}

func (m *RemoteControl) Reset()                    { *m = RemoteControl{} }
func (m *RemoteControl) String() string            { return proto.CompactTextString(m) }
func (*RemoteControl) ProtoMessage()               {}
func (*RemoteControl) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RemoteControl) GetKey() uint32 {
	if m != nil {
		return m.Key
	}
	return 0
}

type Event struct {
	Head      *UltraSonic    `protobuf:"bytes,1,opt,name=Head" json:"Head,omitempty"`
	Sensor    *InfraRed      `protobuf:"bytes,2,opt,name=Sensor" json:"Sensor,omitempty"`
	Remote    *RemoteControl `protobuf:"bytes,3,opt,name=Remote" json:"Remote,omitempty"`
	TimeStamp uint32         `protobuf:"varint,4,opt,name=TimeStamp" json:"TimeStamp,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Event) GetHead() *UltraSonic {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *Event) GetSensor() *InfraRed {
	if m != nil {
		return m.Sensor
	}
	return nil
}

func (m *Event) GetRemote() *RemoteControl {
	if m != nil {
		return m.Remote
	}
	return nil
}

func (m *Event) GetTimeStamp() uint32 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func init() {
	proto.RegisterType((*Speed)(nil), "elegoo.Speed")
	proto.RegisterType((*Command)(nil), "elegoo.Command")
	proto.RegisterType((*UltraSonic)(nil), "elegoo.UltraSonic")
	proto.RegisterType((*InfraRed)(nil), "elegoo.InfraRed")
	proto.RegisterType((*RemoteControl)(nil), "elegoo.RemoteControl")
	proto.RegisterType((*Event)(nil), "elegoo.Event")
}

func init() { proto.RegisterFile("elegoo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x51, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x65, 0x6d, 0x1a, 0xe3, 0xb4, 0x81, 0xba, 0x20, 0x04, 0xf1, 0x50, 0x23, 0x48, 0x2e, 0xf6,
	0x50, 0xfd, 0x01, 0x4d, 0x15, 0xc5, 0x9c, 0x26, 0x7a, 0xf1, 0x16, 0xdb, 0xa9, 0x04, 0x9b, 0x9d,
	0xb0, 0x5d, 0x04, 0x7f, 0xc8, 0xef, 0x94, 0xdd, 0x6c, 0x0c, 0xde, 0xe6, 0xbd, 0x79, 0x99, 0xf7,
	0xf2, 0x16, 0xa6, 0xb4, 0xa3, 0x0f, 0xe6, 0x45, 0xab, 0xd9, 0xb0, 0x0c, 0x3b, 0x94, 0x5e, 0xc0,
	0xb8, 0x6c, 0x89, 0x36, 0x72, 0x0a, 0xa2, 0x48, 0xc4, 0x5c, 0x64, 0xc7, 0x28, 0x0a, 0x8b, 0x30,
	0x39, 0xe8, 0x10, 0xa6, 0x06, 0x0e, 0x73, 0x6e, 0x9a, 0x4a, 0x6d, 0x64, 0xaf, 0x77, 0xd2, 0xc9,
	0x32, 0x5e, 0xf8, 0xab, 0x8e, 0x44, 0x7f, 0x4b, 0x42, 0x50, 0x1a, 0x6e, 0x93, 0xd1, 0x5c, 0x64,
	0x11, 0xba, 0xd9, 0x72, 0x05, 0xf3, 0x67, 0x12, 0xcc, 0x45, 0x16, 0xa3, 0x9b, 0xe5, 0x19, 0x1c,
	0xd9, 0xdd, 0xed, 0xd6, 0x90, 0x4e, 0xc6, 0x6e, 0x31, 0x10, 0xe9, 0x03, 0xc0, 0xeb, 0xce, 0xe8,
	0xaa, 0x64, 0x55, 0xaf, 0xe5, 0x29, 0x44, 0xab, 0x7a, 0x6f, 0x2a, 0xb5, 0x26, 0xe7, 0x1d, 0xe3,
	0x1f, 0xb6, 0x77, 0x56, 0xb5, 0xa6, 0xb5, 0xa9, 0x59, 0xf9, 0xd4, 0x03, 0x91, 0xde, 0x40, 0xf4,
	0xa4, 0xb6, 0xba, 0xc2, 0xee, 0x2f, 0xd1, 0x7d, 0x1e, 0xa1, 0x40, 0x8b, 0x72, 0xa7, 0x8f, 0x50,
	0xe4, 0x5d, 0x03, 0x5d, 0x64, 0x51, 0xa4, 0xe7, 0x10, 0x23, 0x35, 0x6c, 0x28, 0x67, 0x65, 0x34,
	0xef, 0xe4, 0x0c, 0x46, 0xcf, 0xf4, 0xed, 0xbd, 0xed, 0x98, 0xfe, 0x08, 0x18, 0xdf, 0x7f, 0x91,
	0x32, 0xf2, 0x12, 0x82, 0x47, 0xaa, 0xfa, 0x52, 0x64, 0x5f, 0xca, 0x10, 0x1f, 0xdd, 0x5e, 0x66,
	0x10, 0x96, 0xa4, 0xf6, 0xac, 0x9d, 0xeb, 0x64, 0x39, 0xeb, 0x95, 0x7d, 0x40, 0xf4, 0x7b, 0x79,
	0x05, 0x61, 0x67, 0xef, 0x12, 0x4d, 0x96, 0x27, 0xbd, 0xf2, 0x5f, 0x28, 0xf4, 0x22, 0xdb, 0xc0,
	0x4b, 0xdd, 0x50, 0x69, 0xaa, 0xa6, 0xf5, 0x15, 0x0f, 0xc4, 0x5d, 0xf8, 0x16, 0x34, 0x55, 0xad,
	0xde, 0x43, 0xf7, 0xf6, 0xd7, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x01, 0x9b, 0xf8, 0x59, 0x0b,
	0x02, 0x00, 0x00,
}
