/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Tue Jan 24 21:09:08 2017. */

#include "elegoo.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Command_fields[3] = {
    PB_FIELD(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, Command, SetSpeed, SetSpeed, &Speed_fields),
    PB_FIELD(  2, BOOL    , OPTIONAL, STATIC  , OTHER, Command, Stop, SetSpeed, 0),
    PB_LAST_FIELD
};

const pb_field_t Speed_fields[3] = {
    PB_FIELD(  1, INT32   , OPTIONAL, STATIC  , FIRST, Speed, Left, Left, 0),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, Speed, Right, Left, 0),
    PB_LAST_FIELD
};

const pb_field_t Event_fields[5] = {
    PB_FIELD(  1, INT32   , OPTIONAL, STATIC  , FIRST, Event, Distance, Distance, 0),
    PB_FIELD(  2, BOOL    , OPTIONAL, STATIC  , OTHER, Event, SensorA, Distance, 0),
    PB_FIELD(  3, BOOL    , OPTIONAL, STATIC  , OTHER, Event, SensorB, SensorA, 0),
    PB_FIELD(  4, BOOL    , OPTIONAL, STATIC  , OTHER, Event, SensorC, SensorB, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Command, SetSpeed) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Command_Speed_Event)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Command, SetSpeed) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_Command_Speed_Event)
#endif


/* @@protoc_insertion_point(eof) */
