// Code generated by protoc-gen-go. DO NOT EDIT.
// source: elegoo.proto

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	elegoo.proto

It has these top-level messages:
	Command
	Event
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Command struct {
	LeftSpeed  int32 `protobuf:"varint,1,opt,name=LeftSpeed" json:"LeftSpeed,omitempty"`
	RightSpeed int32 `protobuf:"varint,2,opt,name=RightSpeed" json:"RightSpeed,omitempty"`
	TurnHead   int32 `protobuf:"zigzag32,3,opt,name=TurnHead" json:"TurnHead,omitempty"`
	Center     bool  `protobuf:"varint,4,opt,name=Center" json:"Center,omitempty"`
}

func (m *Command) Reset()                    { *m = Command{} }
func (m *Command) String() string            { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()               {}
func (*Command) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Command) GetLeftSpeed() int32 {
	if m != nil {
		return m.LeftSpeed
	}
	return 0
}

func (m *Command) GetRightSpeed() int32 {
	if m != nil {
		return m.RightSpeed
	}
	return 0
}

func (m *Command) GetTurnHead() int32 {
	if m != nil {
		return m.TurnHead
	}
	return 0
}

func (m *Command) GetCenter() bool {
	if m != nil {
		return m.Center
	}
	return false
}

type Event struct {
	Distance int32  `protobuf:"varint,1,opt,name=Distance" json:"Distance,omitempty"`
	SensorR  bool   `protobuf:"varint,2,opt,name=SensorR" json:"SensorR,omitempty"`
	SensorC  bool   `protobuf:"varint,3,opt,name=SensorC" json:"SensorC,omitempty"`
	SensorL  bool   `protobuf:"varint,4,opt,name=SensorL" json:"SensorL,omitempty"`
	KeyPress uint32 `protobuf:"varint,5,opt,name=KeyPress" json:"KeyPress,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Event) GetDistance() int32 {
	if m != nil {
		return m.Distance
	}
	return 0
}

func (m *Event) GetSensorR() bool {
	if m != nil {
		return m.SensorR
	}
	return false
}

func (m *Event) GetSensorC() bool {
	if m != nil {
		return m.SensorC
	}
	return false
}

func (m *Event) GetSensorL() bool {
	if m != nil {
		return m.SensorL
	}
	return false
}

func (m *Event) GetKeyPress() uint32 {
	if m != nil {
		return m.KeyPress
	}
	return 0
}

func init() {
	proto.RegisterType((*Command)(nil), "Command")
	proto.RegisterType((*Event)(nil), "Event")
}

func init() { proto.RegisterFile("elegoo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xbd, 0x4a, 0xc0, 0x30,
	0x14, 0x46, 0x89, 0xf6, 0xcf, 0x8b, 0x0e, 0x66, 0x90, 0x20, 0x22, 0xa1, 0x53, 0x26, 0x17, 0xdf,
	0xc0, 0x28, 0x08, 0x76, 0x90, 0xd4, 0xc9, 0x2d, 0xda, 0x6b, 0x2d, 0xd8, 0xa4, 0x24, 0x51, 0x10,
	0x9f, 0xc1, 0x77, 0x96, 0x86, 0x34, 0x75, 0x3c, 0xdf, 0xe1, 0x72, 0xe0, 0xc2, 0x31, 0x7e, 0xe0,
	0x68, 0xed, 0xd5, 0xe2, 0x6c, 0xb0, 0xed, 0x0f, 0xd4, 0xd2, 0xce, 0xb3, 0x36, 0x03, 0xbd, 0x80,
	0xa3, 0x0e, 0xdf, 0x42, 0xbf, 0x20, 0x0e, 0x8c, 0x70, 0x22, 0x4a, 0xb5, 0x0f, 0xf4, 0x12, 0x40,
	0x4d, 0xe3, 0x7b, 0xd2, 0x07, 0x51, 0xff, 0x5b, 0xe8, 0x39, 0x34, 0x4f, 0x9f, 0xce, 0xdc, 0xa3,
	0x1e, 0xd8, 0x21, 0x27, 0xe2, 0x54, 0x65, 0xa6, 0x67, 0x50, 0x49, 0x34, 0x01, 0x1d, 0x2b, 0x38,
	0x11, 0x8d, 0x4a, 0xd4, 0xfe, 0x12, 0x28, 0xef, 0xbe, 0xd0, 0x84, 0xf5, 0xfa, 0x76, 0xf2, 0x41,
	0x9b, 0x57, 0x4c, 0xe9, 0xcc, 0x94, 0x41, 0xdd, 0xa3, 0xf1, 0xd6, 0xa9, 0x98, 0x6d, 0xd4, 0x86,
	0xbb, 0x91, 0x31, 0x99, 0x8d, 0xdc, 0x4d, 0x97, 0x92, 0x1b, 0xae, 0xa5, 0x07, 0xfc, 0x7e, 0x74,
	0xe8, 0x3d, 0x2b, 0x39, 0x11, 0x27, 0x2a, 0xf3, 0x4d, 0xf5, 0x5c, 0xcc, 0x7a, 0x32, 0x2f, 0x55,
	0xfc, 0xcd, 0xf5, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x81, 0x6c, 0x06, 0xb3, 0x2b, 0x01, 0x00,
	0x00,
}
