// Code generated by protoc-gen-go. DO NOT EDIT.
// source: elegoo.proto

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	elegoo.proto

It has these top-level messages:
	Command
	Event
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Command struct {
	SpeedR   int32 `protobuf:"zigzag32,1,opt,name=SpeedR" json:"SpeedR,omitempty"`
	SpeedL   int32 `protobuf:"zigzag32,2,opt,name=SpeedL" json:"SpeedL,omitempty"`
	Stop     bool  `protobuf:"varint,3,opt,name=Stop" json:"Stop,omitempty"`
	Center   bool  `protobuf:"varint,4,opt,name=Center" json:"Center,omitempty"`
	TurnHead int32 `protobuf:"zigzag32,5,opt,name=TurnHead" json:"TurnHead,omitempty"`
	Trim     int32 `protobuf:"zigzag32,6,opt,name=Trim" json:"Trim,omitempty"`
}

func (m *Command) Reset()                    { *m = Command{} }
func (m *Command) String() string            { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()               {}
func (*Command) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Command) GetSpeedR() int32 {
	if m != nil {
		return m.SpeedR
	}
	return 0
}

func (m *Command) GetSpeedL() int32 {
	if m != nil {
		return m.SpeedL
	}
	return 0
}

func (m *Command) GetStop() bool {
	if m != nil {
		return m.Stop
	}
	return false
}

func (m *Command) GetCenter() bool {
	if m != nil {
		return m.Center
	}
	return false
}

func (m *Command) GetTurnHead() int32 {
	if m != nil {
		return m.TurnHead
	}
	return 0
}

func (m *Command) GetTrim() int32 {
	if m != nil {
		return m.Trim
	}
	return 0
}

type Event struct {
	Distance uint32 `protobuf:"varint,1,opt,name=Distance" json:"Distance,omitempty"`
	SensorR  bool   `protobuf:"varint,2,opt,name=SensorR" json:"SensorR,omitempty"`
	SensorC  bool   `protobuf:"varint,3,opt,name=SensorC" json:"SensorC,omitempty"`
	SensorL  bool   `protobuf:"varint,4,opt,name=SensorL" json:"SensorL,omitempty"`
	KeyPress uint32 `protobuf:"varint,5,opt,name=KeyPress" json:"KeyPress,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Event) GetDistance() uint32 {
	if m != nil {
		return m.Distance
	}
	return 0
}

func (m *Event) GetSensorR() bool {
	if m != nil {
		return m.SensorR
	}
	return false
}

func (m *Event) GetSensorC() bool {
	if m != nil {
		return m.SensorC
	}
	return false
}

func (m *Event) GetSensorL() bool {
	if m != nil {
		return m.SensorL
	}
	return false
}

func (m *Event) GetKeyPress() uint32 {
	if m != nil {
		return m.KeyPress
	}
	return 0
}

func init() {
	proto.RegisterType((*Command)(nil), "Command")
	proto.RegisterType((*Event)(nil), "Event")
}

func init() { proto.RegisterFile("elegoo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xb1, 0x4a, 0xc5, 0x30,
	0x14, 0x86, 0x89, 0xb6, 0x69, 0x09, 0x76, 0x30, 0x83, 0x04, 0xa7, 0xd2, 0xa9, 0x93, 0x8b, 0x6f,
	0x60, 0x15, 0x04, 0x3b, 0x48, 0xda, 0xc9, 0x2d, 0xda, 0x83, 0x14, 0x4c, 0x52, 0x92, 0x28, 0xf8,
	0x10, 0x8e, 0xbe, 0xef, 0x25, 0x87, 0x34, 0xbd, 0xdb, 0xf9, 0xfe, 0x93, 0xfc, 0xf9, 0x08, 0xbb,
	0x82, 0x2f, 0xf8, 0xb4, 0xf6, 0x6e, 0x73, 0x36, 0xd8, 0xee, 0x9f, 0xb0, 0x6a, 0xb0, 0x5a, 0x2b,
	0xb3, 0xf0, 0x1b, 0x46, 0xa7, 0x0d, 0x60, 0x91, 0x82, 0xb4, 0xa4, 0xbf, 0x96, 0x89, 0x72, 0x3e,
	0x8a, 0x8b, 0xb3, 0x7c, 0xe4, 0x9c, 0x15, 0x53, 0xb0, 0x9b, 0xb8, 0x6c, 0x49, 0x5f, 0x4b, 0x9c,
	0xe3, 0xd9, 0x01, 0x4c, 0x00, 0x27, 0x0a, 0x4c, 0x13, 0xf1, 0x5b, 0x56, 0xcf, 0xdf, 0xce, 0x3c,
	0x83, 0x5a, 0x44, 0x89, 0x2d, 0x99, 0x63, 0xcf, 0xec, 0x56, 0x2d, 0x28, 0xe6, 0x38, 0x77, 0x7f,
	0x84, 0x95, 0x4f, 0x3f, 0x60, 0x42, 0xbc, 0xf9, 0xb8, 0xfa, 0xa0, 0xcc, 0x07, 0xa0, 0x57, 0x23,
	0x33, 0x73, 0xc1, 0xaa, 0x09, 0x8c, 0xb7, 0x4e, 0xa2, 0x5a, 0x2d, 0x77, 0x3c, 0x36, 0x43, 0xd2,
	0xdb, 0xf1, 0xd8, 0x8c, 0x49, 0x71, 0xc7, 0xf8, 0xd2, 0x0b, 0xfc, 0xbe, 0x3a, 0xf0, 0x1e, 0x1d,
	0x1b, 0x99, 0xf9, 0x81, 0xbe, 0x15, 0x5a, 0xad, 0xe6, 0x9d, 0xe2, 0xb7, 0xdd, 0x9f, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x67, 0x52, 0x91, 0x80, 0x46, 0x01, 0x00, 0x00,
}
